name: Biome2Forest
version: ${project.version}
description: changes oceans and jungles to forests
author: Xeph0re
authors: [] 
website:

main: tv.mineinthebox.biomes.Biome2Forest
database: false
depend: []
softdepend: []

commands:

permissions: