name: Biome2Forest
version: {project.version}
description: changes oceans and jungles to forests
author: Xeph0re
authors: [] 
website:

main: tv.mineinthebox.Biome2Forest.biome2forest
database: false
depend: []
softdepend: []

commands:

permissions: